export const movements = [
  {
    id: 1,
    product: 'Tela de algodon',
    movementType: 'salida',
    quantity: 20,
    reason: 'Razón del movimiento',
    category: 'tela',
    date: 'Sat Dec 02 2023',
    location: 'almacen',
    status: 'Aprobado',
  },
  {
    id: 2,
    product: 'Vestido Corte Imperial',
    movementType: 'salida',
    quantity: 10,
    reason: 'Razón del movimiento',
    category: 'vestido',
    date: 'Sat Dec 02 2023',
    location: 'tienda',
    status: 'Pendiente',
  },
  {
    id: 3,
    product: 'TELA DE CORDUROI',
    movementType: 'salida',
    quantity: 5,
    reason: 'Razón del movimiento',
    category: 'tela',
    date: 'Sat Dec 02 2023',
    location: 'almacen',
    status: 'Aprobado',
  },
];

export const exactitudInventario = [
  {
    id: 1,
    producto: 'Cheongsam',
    cantidad: '35',
    cantidad_fisico: '28',
    fecha: '21/10/2023',
    resultado: 28 / 35,
  },
  {
    id: 2,
    producto: 'Corte ablusado',
    cantidad: '35',
    cantidad_fisico: '27',
    fecha: '21/10/2023',
    resultado: (27 / 35).toFixed(2),
  },
  {
    id: 3,
    producto: 'Corte tubo',
    cantidad: '35',
    cantidad_fisico: '28',
    fecha: '21/10/2023',
    resultado: 28 / 35,
  },
  {
    id: 4,
    producto: 'Escote en V',
    cantidad: '35',
    cantidad_fisico: '28',
    fecha: '21/10/2023',
    resultado: 28 / 35,
  },
  {
    id: 5,
    producto: 'Escote en V',
    cantidad: '35',
    cantidad_fisico: '30',
    fecha: '21/10/2023',
    resultado: (30 / 35).toFixed(2),
  },
  {
    id: 6,
    producto: 'Estilo imperial',
    cantidad: '35',
    cantidad_fisico: '28',
    fecha: '21/10/2023',
    resultado: 28 / 35,
  },
  {
    id: 7,
    producto: 'Flower Power',
    cantidad: '35',
    cantidad_fisico: '26',
    fecha: '21/10/2023',
    resultado: (26 / 35).toFixed(2),
  },
  {
    id: 8,
    producto: 'Holgados',
    cantidad: '35',
    cantidad_fisico: '28',
    fecha: '21/10/2023',
    resultado: 28 / 35,
  },
  {
    id: 9,
    producto: 'Strapples',
    cantidad: '35',
    cantidad_fisico: '28',
    fecha: '21/10/2023',
    resultado: 28 / 35,
  },
  {
    id: 10,
    producto: 'Tela Chalis',
    cantidad: '35',
    cantidad_fisico: '28',
    fecha: '21/10/2023',
    resultado: 28 / 35,
  },
  {
    id: 11,
    producto: 'Tela Crep',
    cantidad: '35',
    cantidad_fisico: '28',
    fecha: '21/10/2023',
    resultado: 28 / 35,
  },
  {
    id: 12,
    producto: 'Tela Guipur',
    cantidad: '35',
    cantidad_fisico: '28',
    fecha: '21/10/2023',
    resultado: 28 / 35,
  },
  {
    id: 13,
    producto: 'Tela Organza',
    cantidad: '35',
    cantidad_fisico: '28',
    fecha: '21/10/2023',
    resultado: 28 / 35,
  },
  {
    id: 14,
    producto: 'Tela algodon',
    cantidad: '35',
    cantidad_fisico: '29',
    fecha: '21/10/2023',
    resultado: (29 / 35).toFixed(2),
  },
  {
    id: 15,
    producto: 'Tela fantasia',
    cantidad: '35',
    cantidad_fisico: '28',
    fecha: '21/10/2023',
    resultado: 28 / 35,
  },
];
