export const movimientos_ficha = [
  {
    producto: 'Cheongsam',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'vestido',
    cantidad: '16',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'Corte ablusado',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'vestido',
    cantidad: '16',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'Corte tubo',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'vestido',
    cantidad: '14',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'Escote en V',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'vestido',
    cantidad: '16',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'Estilo imperial',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'vestido',
    cantidad: '14',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'Flower Power',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'vestido',
    cantidad: '14',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'Holgados',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'vestido',
    cantidad: '16',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'Strapples',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'vestido',
    cantidad: '16',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'Tela Chalis',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'tela',
    cantidad: '12',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'Tela Crep',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'tela',
    cantidad: '14',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'Tela Guipur',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'tela',
    cantidad: '14',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'Tela Organza',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'tela',
    cantidad: '14',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'Tela algodon',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'tela',
    cantidad: '16',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'Tela fantasia',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'tela',
    cantidad: '16',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'Tela licrada',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'tela',
    cantidad: '15',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'Tela mikado',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'tela',
    cantidad: '15',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'Tela sasten raso',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'tela',
    cantidad: '15',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'Tela satin borgoña',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'tela',
    cantidad: '14',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'Tela seda',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'tela',
    cantidad: '14',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'Tela tafetan',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'tela',
    cantidad: '16',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'Tela terciopelo',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'tela',
    cantidad: '16',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'Tela triacetato',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'tela',
    cantidad: '16',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'cintura alta',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'vestido',
    cantidad: '16',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'corte canesu',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'vestido',
    cantidad: '12',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'tela neopreno',
    motivo: 'venta por mayor',
    locacion: 'tienda',
    fecha: '23-10-2023',
    categoria: 'tela',
    cantidad: '12',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'vestido Linea A',
    motivo: 'venta por mayor',
    locacion: 'vestido',
    fecha: '23-10-2023',
    categoria: 'vestido',
    cantidad: '15',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'vestido de fiesta',
    motivo: 'venta por mayor',
    locacion: 'vestido',
    fecha: '23-10-2023',
    categoria: 'vestido',
    cantidad: '15',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'vestido de noche',
    motivo: 'venta por mayor',
    locacion: 'vestido',
    fecha: '23-10-2023',
    categoria: 'vestido',
    cantidad: '14',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'vestido dos tonos',
    motivo: 'venta por mayor',
    locacion: 'vestido',
    fecha: '23-10-2023',
    categoria: 'vestido',
    cantidad: '14',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
  {
    producto: 'vestido sirena',
    motivo: 'venta por mayor',
    locacion: 'vestido',
    fecha: '23-10-2023',
    categoria: 'vestido',
    cantidad: '14',
    aprobacion: 'Aprobado',
    Tipo_Movimiento: 'salida',
  },
];
